SRCS= ../debouncer.sv  ../maze_controller.sv  ../rom.sv  ../rom_dp.sv  ../vga_frame.sv  ../vga_maze_top.sv  ../vga_sync.sv  ../vga_tb.sv
TOP_MODULE=vga_tb

include ~hy220/tools/common/Makefile.include
